version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: instacart_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: instacart
      POSTGRES_PASSWORD: instacart123
      POSTGRES_DB: instacart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: